name: whatsapp_sender
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  file_picker: ^10.3.1
  csv: ^6.0.0
  permission_handler: ^12.0.1
  provider: ^6.1.5
  country_code_picker: ^3.3.0
  excel: ^4.0.6
  intl: 0.20.2
  share_plus: ^11.1.0
  universal_html: ^2.2.4
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  contacts_service: ^0.6.3
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# pubspec.yaml

# ... (other parts of the file) ...

flutter:
  uses-material-design: true
  
  # THIS IS THE CORRECTED ASSET PATH
  assets:
    - assets/l10n/
    - assets/google_logo.png

# pubspec.yaml

# ... (your other settings)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"    

# pubspec.yaml

# ... (your other settings)

flutter_native_splash:
  # This is the background color of your splash screen
  color: "#25D366" # This matches your app's dark theme

  # This is the path to your logo
  image: assets/icons/icon.png

  # (Optional) If you have a different logo for dark mode
  # color_dark: "#121212"
  # image_dark: assets/icons/icon_dark.png

  # This tells the splash screen how to behave on Android and iOS
  android_12:
    color: "#121212"
    image: assets/icons/icon.png  