// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOr-JlxhmpNEg4tD0LjXjjWC1aB2hv5H8',
    appId: '1:372096838354:web:c77a5ab1cc24cffc6fdb0b',
    messagingSenderId: '372096838354',
    projectId: 'whatsapp-sender-app-799b5',
    authDomain: 'whatsapp-sender-app-799b5.firebaseapp.com',
    storageBucket: 'whatsapp-sender-app-799b5.firebasestorage.app',
    measurementId: 'G-LJ1HEBPKSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJAH1Sv0Wb-NfPmDng2J4bpZd55icZytM',
    appId: '1:372096838354:android:3cd18e99374be8d46fdb0b',
    messagingSenderId: '372096838354',
    projectId: 'whatsapp-sender-app-799b5',
    storageBucket: 'whatsapp-sender-app-799b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIeaH2uJeKFBcc72qgpceAJZWvB4z_Ys',
    appId: '1:372096838354:ios:b5a771ef15bd14246fdb0b',
    messagingSenderId: '372096838354',
    projectId: 'whatsapp-sender-app-799b5',
    storageBucket: 'whatsapp-sender-app-799b5.firebasestorage.app',
    iosBundleId: 'com.example.whatsappSender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIeaH2uJeKFBcc72qgpceAJZWvB4z_Ys',
    appId: '1:372096838354:ios:b5a771ef15bd14246fdb0b',
    messagingSenderId: '372096838354',
    projectId: 'whatsapp-sender-app-799b5',
    storageBucket: 'whatsapp-sender-app-799b5.firebasestorage.app',
    iosBundleId: 'com.example.whatsappSender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOr-JlxhmpNEg4tD0LjXjjWC1aB2hv5H8',
    appId: '1:372096838354:web:37cfec8e1d1d8bf66fdb0b',
    messagingSenderId: '372096838354',
    projectId: 'whatsapp-sender-app-799b5',
    authDomain: 'whatsapp-sender-app-799b5.firebaseapp.com',
    storageBucket: 'whatsapp-sender-app-799b5.firebasestorage.app',
    measurementId: 'G-9XSBYXYEHD',
  );
}
